---
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - VERSION=docker
      - PLEX_CLAIM= #Optionally you can obtain a claim token from https://plex.tv/claim and input here. Keep in mind that the claim tokens expire within 4 minutes.
    volumes:
      - /media/downloads:/config
      - /media/downloads/complete:/tv
      - /media/downloads/complete:/movies
    restart: unless-stopped
    # For Intel GPU need device=/dev/dri:/dev/dri
